<?php 
$q = array();
$q[0] = "A job pays \$6 per hour for the first 40 hours per week, and \$9 per hour for overtime. If you work 46 hours a week, what will you earn?|\$276|\$294|\$303|\$396";
$q[1] = "A woman has an estate of \$10,000. She leaves 1/10 to charity. Her daughter gets 2/3 of the remainder. How much money does her daughter get?|\$6667|\$6000|\$667|\$600";
$q[2] = "The number 8 is 20% of what number?|160|16|4|40";
$q[3] = "A car dealer is offering 15% off on all vehicles. If the original cost of a car is \$16,000, what is its sale?|\$15,000|\$14,500|\$14,000|\$13,600";
$q[4] = "A theater owner wants to be able to seat 1250 people. The main floor has 30 rows of 25 seats each. If the balcony has 25 rows, how many seats must be in each row?|40|30|25|20";
$q[5] = "Solve for x:  2x - 3 = 5x + 4|x = -7/3|x = -3/7|x = 1/7|x = 1/3";
$q[6] = "How the statement 'x is 2 more than y' is written in mathematical form?| x + 2 = y| x = 2 + y| x + y = 2| x + 2 > y";
$q[7] = "A box with a square base has a volume of 16 cubic feet. If the base of the box measures 2 feet by 2 feet, how tall is the box?| 2 feet| 4 feet| 8 feet| 32 feet";
$q[8] = "The y-intercept of the line <b>y - 3x = 2</b> is|5|3|2|1";
$q[9] = "The area of the base of a cube is 5 square inches. What is the surface area?| 20 square inches| 25 square inches| 30 square inches| 100 square inches";
$q[10] = "Solve for x: 3x > x + 12 | x < 6| x < 3| x > 6| x > 4";
$q[11] = "The graph of the line 2x + y = 6| has a positive slope| has a negative slope| is horizontal| is vertical";
$q[12] = "Which one of these points lies on the line x - 3y = 5 ?| (-1, 2)| (1, -2)| (2, 1)| (2, -1)";
$q[13] = "Two straight lines in same plane which never meet are called |angles|transversal lines|vertex|parallel lines";
$q[14] = "Which one of these points is not included in the graph of -2 < 2x - 3 ?| 0| 1| 2| 3";
$q[15] = "A statement in which sign of equality “ = ” is used to link two algebric expressions is called | formula | equation | fraction | matrix ";
$q[16] = "If it costs \$ 0.25 per mile to drive a car, how much will it cost (in dollars) to drive 'd' miles?| d - 0.25| d + 0.25| d / 0.25| 0.25 d";
$q[17] = "Ahmed bought a used car for \$6000 and paid 15% deposit. How much did he still have to pay?|\$900|\$5000|\$4500|\$5100";
$q[18] = "What is 8% of \$600?|\$580|\$480|\$48|\$58";
$q[19] = "Which is the longest distance?|3500cm|65.5m|75000mm|0.01km";
$q[20] = "Concrete is made by mixing screenings cement and sand in the ratio 3:1:15. How much sand would be needed to make 125 tonnes of concrete?|27 tonnes|33.75 tonnes|45 tonnes|75 tonnes";
$q[21] = "Sam bought a car valued at \$7700. One year later the car's value had decreased by 2/7. What is the new value of the car?|\$2200|\$5500|\$9900|\$4400";
$q[22] = "Which of the following is a set of prime numbers? | {0,2,4,6,8} | {1,3,5,7,9} | {2,3,5,8,11} | {2,3,5,7,11}";
$q[23] = "Aisha placed blocks on a table in rows and columns. All the rows and columns had the same number of blocks in them and formed a square. Which could be the total number of blocks Aisha placed on the table? | 111 blocks | 121 blocks | 181 blocks | 222 blocks";
$q[24] = "If log5 = 0.6990 and log3 = 0.4771 , then log 45 =  | 0.93755 | 0.1591 | 2.3524 | 2.1303";
$q[25] = "Given that a circle has 2 <i>pi</i> radians, how many circles are equal to 12 <i>pi<i> radians? | 6 | 12 | 15 | 20 ";
$q[26] = "The sum of a number and 6 is 8 more than twice the number. If the number is x, the statement can be written as:|x + 6 = 2x + 8|x + 6 = 2(x + 8)|6x = 2x + 8|x + 14 = 2x ";
$q[27] = "Perform the indicated operation and write the result in standard form: (-3 + 2i )( -3 - 7i ) |-5 + 27i|23 + 15i|23 - 15i|-5 - 27i";
$q[28] = "Which expression is equivalent to 7 x (2 + 3)? | (7 x 2) + (7 x 3) | (7 + 2) x (7 + 3) | (7 x 2) x (7 x 3) | (7 + 2) x 3";
$q[29] = "For what value of 'x' will the equation  <strong> x - (2x/3  + 1) = 0 </strong> be satisfied? | x = 1 | x = 2 | x = 3 | x = 4";
$q[30] = "What is the speed in m/s of a car that travels 30km in 20 minutes? | 1500 m/s | 150 m/s | 90 m/s | 25 m/s";
$q[31] = "Jack's Dad invested some money and for every \$12 he invested he got a total of \$15 back. If Jack's Dad invested \$300, how much in total did he get back? | \$225 | \$525 | \$480 | \$375";
$q[32] = "If bus conductor issues 50 tickets in 30 minutes, how many tickets can he issue in 8 hrs.? | 400 | 600 | 800 | 1000";
$q[33]="3, 7, 11, 15, 19. In this sequence what number comes next? | 20 | 21 | 22 | 23";
$q[34]="27, 30, 33, ___, ___, 42. What set of numbers complete this sequence? | 34, 35 | 35, 38 | 36, 39 | 35, 39";
$q[35]="18, 24, 30, ___, 42. What is the missing number? | 36 | 38 | 40 | 42";
$q[36]="21, 24, ___, 30. What is the missing number? | 25 | 26 | 27 | 28";
$q[37]="Worker A completes a job in 10 days and Worker B completes the same job in 15 days. In how many days they will complete the job together? | 5 | 6 | 7 | 8";
$q[38]="Two pipes can fill the tank in 10 hr and 12 hr respectively, while the third pipe can empty it in 20 hour simultaneously, if all the pipes are opened then the tank will be filled in: | 7.5 | 8 | 5 | 10";
$q[39]="15 men take 20 days to complete a job working 8 hours a day. How many  hours a day should 20 men take to complete the job in 12 days? | 5 | 10 | 15 | 20";
$q[40]="Shahid can do a work in 50 days and Basit is 50% efficient than Shahid.In how many days Shahid and Basit together can complete the work? | 33.33 | 30 | 16.67 | 40";
$q[41]="If bus conductor issues 50 tickets in 30 minute how many tickets can he be able to issues in 8 hrs.? | 600 | 800 | 1000 | 1200";
$q[42]="A line that touches a curve at one point, without passing or cutting, is referred as: | chord | arc | radius | tangent";
$q[43]="Which of the following is not part of Plane Geometry? | Line | Triangle  | Circle | Sphere";
$q[44]="Which of the following is One-dimensional? | Line | Circle | Star | Triangle";
$q[45]="Which of the following has ZERO dimension? | Point | Line | Circle | Angle";
$q[46]="Which of the following is TWO-dimensional? | Line | Circle | Sphere | Cylinder";
$q[47]="In a small company average salary of three employees is Rs. 1000 per week. If one employee earns Rs. 1100 and other earns Rs. 500, how much will the third employee earn? | 1000 | 3000 | 1400 | 1200";
$q[48]="A line which connects any two points on a circle is known as | perimeter | diameter | chord | radius ";
$q[49]="Angles that are opposite to each other are called | vertical angles | complementary angles | reflective angles | supplementary angles ";
$q[50]="Angles that sum up to 90° are known as | vertical angles | complementary angles | reflective angles | supplementary angles ";
$q[51]="A triangle that has 2 equal sides and 2 equal angles is known as | isosceles triangle | equilateral triangle | scalene triangle | right angle ";
$q[52]="A line from center to circumference of a circle is known as | diameter | radius | area | midpoint ";
$q[53]="A polygon having 5 sides is called | pentagon | hexagon | nonagon | decagon ";
$q[54]="In terms of radius, a diameter is equals to | 2 + r | 2r | r⁄2 | 2⁄r ";
$q[55]="Angles that sum up to 180° are known as | complementary angles | reflective angles | supplementary angles | vertical angles ";
$q[56]="Circumference of circle is calculated by | 2πr | 2π⁄r | πr⁄2 | πr ";
$q[57]="If radius of a circle is increased by 30% then its area is increased by | 0.4 | 0.69 | 0.7 | 0.5 ";
$q[58]="Area of circle is calculated by | π⁄r² | πr² | π²r | r²⁄π ";
$q[59]="A polygon having 9 sides is called | decagon | quadrilateral | nonagon | hexagon ";
$q[60]="Surface area of solid cylinder with radius ‘r’ and height ‘h’ is measured by | 2πrh + 2πr² | 2πrh - 2πr² | πrh - πr² | πrh + πr² ";
$q[61]="When a polygon's all sides and angles are equal, it is said to be | reflective | quadrilateral | regular | vertical ";
$q[62]="Angles that are greater than 180° and less than 360° are called | reflective angles | obtuse angles | acute angles | right angles ";
$q[63]="Circle touching one side of triangle externally and two produced sides internally is called | circumangle | circumference | e - circle | e - centre ";
$q[64]="Interior angles of any triangle sum up to | 90° | 180° | 270° | 360° ";
$q[65]="Volume of a cylinder with radius ‘r’ and height ‘h’ is measured by | πr²⁄h | πh²⁄r | πr²h | πr × h ";
$q[66]="If x - a is a factor of P(x), then P(a) should be | 1 | 0 | a | −a ";
$q[67]="(a + b)² + (a - b)² is equal to | 2ab | 2a² - 2b² | 4ab | 2a² + 2b² ";
$q[68]="Which one is irrational number ? | 2⁄3 | √4 | 3⁄5 | 3⁄7 ";
$q[69]="(a + b)² - (a - b)² is equal to | 2ab | a² - b² | 4ab | a² + b² ";
$q[70]="a³ - 3ab(a - b) - b³ is equal to | (a - b)³ | (a + b)³ | a³ + b³ | a³ - b³ ";
$q[71]="If a + b = 5 and a - b = √17 then value of ab should be | 3 | 2 | 5 | 4 ";
$q[72]="A well defined collection of objects is known as | population | fraction | equation | set ";
$q[73]="If U={1, 2, 3, 4, 5} and A={2, 4} then A' should be | {2, 4, 5} | {2, 4} | {1, 2, 3, 4, 5} | {1, 3, 5} ";
$q[74]="A set with no element in it is known as | subset | singleton set | power set | empty set ";
$q[75]="We can subtract two matrices A and B if their | elements are same | order is same | rows are same | columns are same ";
$q[76]="A matrix obtained by changing rows into columns or vice versa is called | additive inverse of A | transpose of A | determinant of A | order of A ";
$q[77]="If A, B and C matrices are of same order and (A + B) + C = A + (B + C), this law is known as | Cramer's law | distributive law | commutative law | associative law ";
$q[78]="Law which does not hold in multiplication of matrices is known as | distributive law | Inverse law | associative law | commutative law ";
$q[79]="If At = −A then A is said to be | square matrix | skew symmetric | transpose | symmetric ";
$q[80]="A square matrix in which all elements except at least one element in diagonal are zeros is said to be a | identical matrix | null/zero matrix | column matrix | diagonal matrix ";
$q[81]="A pair of equations to determine value of 2 variables is called | simultaneous linear equations | paired equations | quadratic equations | simple equations ";
$q[82]="If two matrices A and B have same order and their corresponding elements are equal then it is called | matrix equality | rectangular matrix | square matrix | identical matrix ";
$q[83]="If number of rows in A matrix are equal to number of column in B matrix, then A and B are comfortable for | product | division | transpose | making identity ";
$q[84]="A scalar matrix having each element equal to 1 is said to be | unit or identical matrix | rectangular matrix | square matrix | diagonal matrix ";
$q[85]="If A and B matrices are of same order and A + B = B + A, this law is known as | distributive law | commutative law | associative law | Cramer's law ";
$q[86]="If sum of two matrices A and B is zero matrix, then A and B are said to be | multiplicative inverse of each other | additive inverse of each other | transpose of each other | determinant of each other ";
$q[87]="If A(BC) = (AB)C, then with respect to multiplication this law is called | Inverse law | associative law | cramers law | additive law ";
$q[88]="Number of terms in a standard quadratic equation ax² + bx + c = 0 is | 1 | 2 | 3 | 4 ";
$q[89]="Solution set of equation x² - 4 = 0 is | {±4} | {4} | {±2} | {2} ";
$q[90]="Solution set of equation x² - 4x + 4 = 0 is | {±4} | {4} | {±2} | {2} ";
$q[91]="Value of third proportional to a³, 3a² should be | 9a | 12a | 9a² | 12a² ";
$q[92]="Value of third proportional to 4, 12 should be | 33 | 34 | 35 | 36 ";
$q[93]="If 2, x, 8 are in continued proportional, then value of x should be | ±2 | ±4 | 2 | 4 ";
$q[94]="Value of mean proportional to 20, 45 should be | ±30 | −30 | −900 | ±900 ";
$q[95]="Value of fourth proportional to 5, 8, 15 should be | 21 | 22 | 24 | 26 ";
$q[96]="If three quantities a, b and c are related as a : b : : b : c, then c is called | third proportional | fourth proportional | mean proportional | continued proportional ";
$q[97]="If 3 quantities a, b and c are related as a : b : : b : c, then b is called | third proportional | fourth proportional | mean proportional | continued proportional ";
$q[98]="Angles between 0° and 90° lies in | 2nd quadrant | 3rd quadrant | 1st quadrant | 4th quadrant ";
$q[99]="System in which angles are measured in radians is called | CGS system | MKS system | circular system | sexagesimal system ";
$q[100]="Value of 240° into radians should be | 4π⁄3 | 3π⁄4 | π⁄4 | π⁄6 ";
$q[101]="We can divide circumference of a circle into | 180 equal arcs | 360 equal arcs | 270 equal arcs | 90 equal arcs ";
$q[102]="Union of two non-collinear rays with some common end point is called | vertex | angle | degree | radius ";
$q[103]="A part of circumference of a circle is called | segment | radius | sector | arc ";
$q[104]="In an angle, rays of angle are known as | arms | vertex | point of intersection | initial side ";
$q[105]="π radians are equal to | 180° | 360° | 90° | 270° ";
$q[106]="Tanθ equals to | 1⁄cosecθ | 1⁄secθ | 1⁄cosθ | 1⁄cotθ ";
$q[107]="Angles between 90° and 180° lies in | 1st quadrant | 2nd quadrant | 3rd quadrant | 4th quadrant ";
$q[108]="3π⁄2 radians are equal to | 270° | 180° | 90° | 60° ";
$q[109]="1 + tan²θ equals to | cosec²θ | sec²θ | sin²θ | cos²θ ";
$q[110]="If length is 2 cm and radius is 3.5 cm, value of θ should be | 0.36 radians | 0.57 radians | 1.46 radians | 2.74 radians ";
$q[111]="sin²θ + cos²θ equals to | 1 | 0 | 0.5 | 2 ";
$q[112]="Angles between 270° and 360° lies in | 1st quadrant | 2nd quadrant | 3rd quadrant | 4th quadrant ";
$q[113]="Value of 5π⁄6 into degrees should be | 135° | 90° | 120° | 150° ";
$q[114]="If length of an arc is 52 cm and θ is 45°, then radius of the arc should be | 56.7 cm | 60 cm | 66.21 cm | 49 cm ";
$q[115]="Sinθ equals to | 1⁄cosecθ | 1⁄secθ | 1⁄cosθ | 1⁄tanθ ";
$q[116]="Cosθ equals to | 1⁄cosecθ | 1⁄secθ | 1⁄tanθ | 1⁄cotθ ";
$q[117]="1 + cot²θ equals to | sec²θ | sin²θ | cosec²θ | cos²θ ";
$q[118]="If θ is 180° and radius is 4.9 cm, then the length of the arc should be | 15.4 cm | 16 cm | 10 cm | 13.6 cm ";
$q[119]="A part of circle bounded by two radii and an arc is known as | segment | radius | sector | arc ";
$q[120]="Value of 30° into radians should be | π⁄3 | π⁄4 | π⁄6 | 2π⁄4 ";
$q[121]="X-axis and y-axis divides the plane in four regions, called | quadrants | segments | sectors | positions ";
$q[122]="Fundamental trigonometric ratios are | 4 | 5 | 6 | 3 ";
$q[123]="Angle subtended at centre of circle by an arc, whose length and radius are equal is called | initial side | radian | vertex | point of intersection ";
$q[124]="Minimum value in class limit is called | primary limit | upper limit | lower limit | secondary limit ";
$q[125]="In a cumulative frequency polygon, frequencies are plotted against | mid point | upper class boundaries | class limits | frequency distribution ";
$q[126]="Total of frequency up to an upper class limit or boundary is known as | average frequency | cumulative frequency | frequency distribution | frequency polygon ";
$q[127]="Data presented in form of frequency data is known as | grouped data | ungrouped data | secondary data | calculated data ";
$q[128]="Most frequent occurring observation in data is called | mean | median | mode | standard deviation ";
$q[129]="A tabular arrangement for classifying data into different groups is called | standard deviation | frequency distribution | class mean | arithmetic mean ";
$q[130]="Constructed on XY - plane, a histogram is a graph of adjacent | squares | circles | rectangles | triangles ";
$q[131]="Statistically, spread or scatterness of observations in a data is called | discriminant | dispersion | range | standard deviation ";
$q[132]="For a variable X, nth positive root of product of x1, x2, x3,.... Xn is called | Arithmetic mean | harmonic mean | standard mean | geometric mean ";
$q[133]="When numbers are associated with weights, then obtained mean is said to be | weighted arithmetic mean | harmonic mean | standard mean | geometric mean ";
$q[134]="Maximum value in class limit is called | primary limit | upper limit | lower limit | secondary limit ";
$q[135]="Arithmetic mean of values 2, 7, 9, 18 is equal to | 7 | 8 | 9 | 11 ";
$q[136]="Difference between maximum and minimum observation is called | mid point | range | mean | median ";
$q[137]="Middle most observation in an arranged data set is known as | mean | median | mode | standard deviation ";
$q[138]="Mean is affected by change in | origin | scale | none | both A and B ";
$q[139]="Positive square root of mean of squared deviations of some observations from their arithmetic mean is called | standard deviation | variation | median | mode ";
$q[140]="Sum of deviations of a variable from its mean is always | 0 | 1 | 2 | 5 ";
$q[141]="Successive averages which are computed for a sequence of days/months/years at a time is called | fixed averages | weighted averages | moving averages | standard averages ";
$q[142]="Difference of any value of variable from a constant is known as | mid point | median | Arithmetic mean | deviation ";
$q[143]="Standard form of quadratic equation is | ax + bx + c = 0 | ax² + bx + c = 0 | ax² + bx - c = 0 | ax² + bx + c = −1";
$q[144]="An equation involving only a linear polynomial is called a | linear equation | quadratic equation | simultaneous equation | inequal equation ";
$q[145]="Linear equation is also called | second degree equation | first degree equation | zero degree equation | simultaneous equation ";
$q[146]="Value of ‘x’ in 6x - 4 = 3x + 8 should be | 3 | 6 | 5 | 4 ";
$q[147]="Solution of x + 3 < 9 is | x > 4 | x < 6 | x < 5 | x = 6 ";
$q[148]="Two linear equations are said to be equivalent if they have exactly same | inequality signs | coefficient | solution | none of the above ";
$q[149]="Solution of 4x - 2 > 6 is | x > 2 | x < 6 | x = 4 | x > 4 ";


$a = array();
$a[0]="b";
$a[1]="a";
$a[2]="d";
$a[3]="d";
$a[4]="d";
$a[5]="a";
$a[6]="a";
$a[7]="b";
$a[8]="c";
$a[9]="c";
$a[10]="c";
$a[11]="b";
$a[12]="d";
$a[13]="d";
$a[14]="a";
$a[15]="b";
$a[16]="d";
$a[17]="c";
$a[18]="c";
$a[19]="d";
$a[20]="b";
$a[21]="b";
$a[22]="d";
$a[23]="b";
$a[24]="b";
$a[25]="a";
$a[26]="a";
$a[27]="b";
$a[28]="a";
$a[29]="c";
$a[30]="d";
$a[31]="d";
$a[32]="c";
$a[33]="d";
$a[34]="c";
$a[35]="a";
$a[36]="c";
$a[37]="b";
$a[38]="a";
$a[39]="b";
$a[40]="a";
$a[41]="b";
$a[42]="d";
$a[43]="d";
$a[44]="a";
$a[45]="a";
$a[46]="b";
$a[47]="c";
$a[48]="c";
$a[49]="a";
$a[50]="b";
$a[51]="a";
$a[52]="b";
$a[53]="a";
$a[54]="b";
$a[55]="c";
$a[56]="a";
$a[57]="b";
$a[58]="c";
$a[59]="c";
$a[60]="a";
$a[61]="c";
$a[62]="a";
$a[63]="c";
$a[64]="b";
$a[65]="c";
$a[66]="b";
$a[67]="d";
$a[68]="b";
$a[69]="c";
$a[70]="a";
$a[71]="c";
$a[72]="d";
$a[73]="d";
$a[74]="d";
$a[75]="b";
$a[76]="b";
$a[77]="d";
$a[78]="d";
$a[79]="b";
$a[80]="d";
$a[81]="a";
$a[82]="a";
$a[83]="a";
$a[84]="a";
$a[85]="b";
$a[86]="b";
$a[87]="b";
$a[88]="c";
$a[89]="c";
$a[90]="d";
$a[91]="d";
$a[92]="b";
$a[93]="a";
$a[94]="a";
$a[95]="a";
$a[96]="c";
$a[97]="c";
$a[98]="c";
$a[99]="a";
$a[100]="b";
$a[101]="b";
$a[102]="b";
$a[103]="d";
$a[104]="a";
$a[105]="a";
$a[106]="d";
$a[107]="b";
$a[108]="a";
$a[109]="b";
$a[110]="b";
$a[111]="a";
$a[112]="d";
$a[113]="d";
$a[114]="c";
$a[115]="a";
$a[116]="b";
$a[117]="c";
$a[118]="a";
$a[119]="c";
$a[120]="c";
$a[121]="a";
$a[122]="c";
$a[123]="c";
$a[124]="b";
$a[125]="b";
$a[126]="b";
$a[127]="a";
$a[128]="c";
$a[129]="b";
$a[130]="c";
$a[131]="d";
$a[132]="d";
$a[133]="a";
$a[134]="b";
$a[135]="c";
$a[136]="b";
$a[137]="b";
$a[138]="a";
$a[139]="a";
$a[140]="a";
$a[141]="c";
$a[142]="d";
$a[143]="b";
$a[144]="a";
$a[145]="b";
$a[146]="d";
$a[147]="b";
$a[148]="c";
$a[149]="a";


?>









