<?php 
$q = array();
$q[0]="The measure of an interior angle of a regular polygon is 120°. How many sides does the polygon have? |  5 |  6 |  3 |  4";
$q[1]="Which of the following is not a Three-dimensional object? | Sphere | Cone | Cyliner | Triangle";
$q[2]="Number should be added to complete square of \(x^4 + 64\) is |  4x² |  16x² |  8x² |  −16x²";
$q[3]="If an algebric expression is exactly divisible by two or more expressions, then expression is said to be |  rational expression |  irrational expression |  common multiple |  second expression";
$q[4]="In algebric fractions, numerators and denominators are |  polynomials |  odd numbers |  even numbers |  surds";
$q[5]="Product of 3 cube roots of unity is/are |  2 |  3 |  4 |  1";
$q[6]="If b² - 4ac < 0, then roots of ax² + bx + c = 0 are |  equal |  irrational |  rational |  imaginary";
$q[7]="Roots of equation 9x² - 9x + 1 = 0 are |  real, equal |  real, unequal |  imaginary |  irrational";
$q[8]="If b² - 4ac >0, and not a perfect square then roots of ax² + bx + c = 0 are |  imaginary |  rational |  equal |  irrational";
$q[9]="If b² - 4ac >0, then roots of ax² + bx + c = 0 are |  irrational |  real |  equal |  rational";
$q[10]="An equation which contains square of unknown variable quantity, but no higher power is called |  quadratic equation |  linear equation |  simple equation complex equation |  complex equation";
$q[11]="Discriminant of 2x² + 5x - 1 is |  25 |  30 |  33 |  35";
$q[12]="When x is replaced by 1⁄x and given equation remains unchanged then it is said to be |  linear equation |  radical equation |  quadratic equation |  reciprocal equation";
$q[13]="If α and β are roots of 3x² + 5x - 2 = 0 then α + β should be |  5⁄2 |  −5⁄3 |  2⁄3 |  3⁄5";
$q[14]="Nature of roots depends on value of b² - 4ac is known as |  discriminant |  square root |  quadratic formula |  completing square method";
$q[15]="An equation involving expression under radical sign is known as |  linear equation |  radical equation |  quadratic equation |  complex equation";
$q[16]="Standard form of quadratic equation is |  ax + bx + c = 0 |  ax² + bx + c = 0 |  ax² + bx - c = 0 |  ax² + bx + c = −1";
$q[17]="A root of an equation, which do not satisfy equation is called |  square root |  reflective root |  extraneous root |  complex root";
$q[18]="If b² - 4ac >0, and perfect square, then roots of ax² + bx + c = 0 are |  irrational |  imaginary |  rational |  equal";
$q[19]="2 square roots of unity are |  1, −1 |  1, ω |  1, −ω |  ω and ω²";
$q[20]="In quadratic equation, if b = 0 then it is called |  linear equation |  simple equation complex equation |  complex equation |  pure quadratic equation";
$q[21]="Method to derive a quadratic formula is |  completing square method |  factorization method |  synthetic method |  using formula method";
$q[22]="Sum of all cube roots of unity is |  1 |  2 |  0 |  3";
$q[23]="Cosec²θ - cot²θ equals to |  1 |  -1 |  0 |  tanθ";
$q[24]="Secθcotθ equals to |  sinθ |  1⁄cosθ |  1⁄sinθ |  sinθ⁄cosθ";
$q[25]="Area of sector with radius ‘r’ is measured by |  1⁄2r |  1⁄2 × r²θ |  2r⁄θ |  2r + θ";
$q[26]="Value obtained by reciprocating mean of reciprocal of x1, x2, x3, .... Xn observations is called |  Arithmetic mean |  harmonic mean |  standard mean |  geometric mean";
$q[27]="Mean of squared deviations of some observations from their arithmetic mean is called |  standard deviation |  variation |  median |  mode";
$q[28]="If a line ‘l’ is perpendicular to line segment and passes through its mid point, then it is called |  concurrent |  collinear |  right bisector |  right angle";
$q[29]="Triangles of same base and of same altitudes are equal in |  angles |  height |  area |  volume";
$q[30]="To draw a ray to divide given angle into 2 equal parts is known as |  congruent |  trisection |  bisection |  segment";
$q[31]="If 2 sides of a triangle are unequal in length, then the angle opposite to the longer side is of  |  equal measure |  greater measure |  smaller measure |  none of above";
$q[32]="If 1 side of a triangle is taken as its base, perpendicular to that side, from opposite vertex is called the |  Altitude or Height |  angle |  volume |  width";
$q[33]="In a scalene triangle, angle opposite to largest side is of measure |  greater than 30° |  greater than 270° |  greater than 90° |  greater than 60°";
$q[34]="Bisectors of angles of a triangle are |  concurrent |  collinear |  opposite |  none of above";
$q[35]="Area of a parallelogram is equal to |  base - altitude |  base/altitude |  base × altitude |  base + altitude";
$q[36]="Difference of measures of two sides of a triangle is less than measure of the |  3rd side |  both 2nd and 3rd side |  1st side |  2nd side";
$q[37]="Sum of lengths of any 2 sides of a triangle is greater than length of the |  1st side |  2nd side |  3rd side |  both 1st and 3rd side";
$q[38]="What are the center and the radius of the circle whose equation is (x − 5)2 + (y + 3)2 = 16? | (−5, 3) and 16 | (5, −3) and 16 | (−5, 3) and 4 | (5, −3) and 4";
$q[39]="The number of degrees in the sum of the interior angles of a pentagon is |  72 |  360 |  540 |  720";
$q[40]="The coordinates of the endpoints of AB are A(0, 0) and B(0, 6). The equation of the perpendicular bisector of AB is |  x = 0 |  x = 3 |  y = 0 |  y = 3";
$q[41]="In scalene triangle ABC, m∠B = 45 and m∠C = 55. What is the order of the sides in length, from longest to shortest? |  AB, BC, AC |  BC, AC, AB |  AC, BC, AB |  BC, AB, AC";
$q[42]="In rhombus ABCD, the diagonals AC and BD intersect at E. If AE = 5 and BE = 12, what is the length of AB? |  7 |  10 |  13 |  17";
$q[43]="A sphere is inscribed inside a cube with edges of 6 cm. In cubic centimeters, what is the volume of the sphere, in terms of π? |  12π |  36π |  48π |  288π";
$q[44]="Which line is parallel to the line whose equation is 4x + 3y = 7 and also passes through the point (−5, 1) ? |  4x + 3y = −26 |  4x + 3y = −14 |  3x + 4y = −7 |  3x + 4y = 14";
$q[45]="In a given triangle, the point of intersection of the three medians is the same as the point of intersection of the three altitudes. Which classification of the triangle is correct? |  scalene triangle |  isosceles triangle |  equilateral triangle |  right isosceles triangle";
$q[46]="Which type of triangle can be drawn using the points (−2, 3), (−2, −7), and (4, −5)? |  scalene |  isosceles | equilateral |  no triangle can be drawn";
$q[47]="Which reason could be used to prove that a parallelogram is a rhombus? |  Diagonals are congruent. |  Opposite sides are parallel. |  Diagonals are perpendicular. |  Opposite angles are congruent";
$q[48]="What is the equation of a line passing through (2, −1)  and parallel to the line represented by the equation y = 2x + 1? |  y = − 1 2 x |  y = − 1 2 x + 1 |  y = 2x − 5 |  y = 2x − 1";
$q[49]="The angle formed by the radius of a circle and a tangent to that circle has a measure of |  45° |  90° |  135° |  180°";
$q[50]="Which quadrilateral has diagonals that always bisect its angles and also bisect each other? |  rhombus |  rectangle |  parallelogram |  isosceles trapezoid";
$q[51]="What is the equation of a circle whose center is 4 units above the origin in the coordinate plane and whose radius is 6? |  x 2 + (y − 6)2 = 16 |  (x − 6)2 + y 2 = 16 |  x 2 + (y − 4)2 = 36 | (x − 4)2 + y 2 = 36";
$q[52]="Given three distinct quadrilaterals, a square, a rectangle, and a rhombus, which quadrilaterals must have perpendicular diagonals? |  the rhombus, only |  the rectangle and the square |  the rhombus and the square |  the rectangle, the rhombus, and the square";
$q[53]="What is the slope of a line perpendicular to the line whose equation is 20x − 2y = 6? |  −10 |  − 1 / 10 |  10 |  1 / 10";
$q[54]="If ∆JKL ≅ ∆MNO, which statement is always true? |  ∠KLJ ≅ ∠NMO |  ∠KJL ≅ ∠MON |  JL ≅ MO |  JK ≅ ON";
$q[55]="What is the measure of each interior angle of a regular hexagon? |  60° |  120° |  135° |  270°";
$q[56]="The volume of a rectangular prism is 144 cubic inches. The height of the prism is 8 inches. Which measurements, in inches, could be the dimensions of the base? |  3.3 by 5.5 |  2.5 by 7.2 |  12 by 8 |  9 by 9";
$q[57]="What is the volume, in cubic centimeters, of a cylinder that has a height of 15 cm and a diameter of 12 cm? |  180π |  540π |  675π |  2, 160π";
$q[58]="The angles of triangle ABC are in the ratio of 8:3:4. What is the measure of the smallest angle? |  12º |  24º |  36º |  72º";
$q[59]="For which polygon does the sum of the measures of the interior angles equal the sum of the measures of the exterior angles? |  hexagon |  pentagon |  quadrilateral |  triangle";
$q[60]="Triangle PQR has angles in the ratio of 2:3:5. Which type of triangle is PQR? |  acute |  isosceles |  obtuse |  right";
$q[61]="Which statement is true about every parallelogram? |  All four sides are congruent. |  The interior angles are all congruent. |  Two pairs of opposite sides are congruent. |  The diagonals are perpendicular to each other";
$q[62]="In circle O, a diameter has endpoints (−5, 4)  and (3, −6). What is the length of the diameter? |  2 |  2 2 |  10 |  2 41";
$q[63]="How many points are both 4 units from the origin and also 2 units from the line y = 4? |  1 |  2 |  3 |  4";
$q[64]="If the vertex angles of two isosceles triangles are congruent, then the triangles must be |  acute |  congruent |  right |  similar";
$q[65]="Which set of numbers does not represent the sides of a right triangle? |  {6, 8, 10} |  {8, 15, 17} |  {8, 24, 25} |  {15, 36, 39}";
$q[66]="Triangle ABC has vertices A(0, 0), B(3, 2), and C(0, 4) . The triangle may be classified as |  equilateral | isosceles |  right |  scalene";
$q[67]="The diagonals of a quadrilateral are congruent but do not bisect each other. This quadrilateral is |  an isosceles trapezoid |  a parallelogram |  a rectangle |  a rhombus";
$q[68]="The volume, in cubic centimeters, of a sphere whose diameter is 6 centimeters is |  12π |  36π |  48π |  288π";
$q[69]="The equations x + y = 25 and y = 5 are graphed on a set of axes. What is the solution of this system? | (0, 0) | (5, 0) | (0, 5) | (5, 5)";
$q[70]="In a coordinate plane, the locus of points 5 units from the x-axis is the |  lines x = 5 and x = −5 |  lines y = 5 and y = −5 |  line x = 5, only |  line y = 5, only";
$q[71]="What is the perimeter of a square whose diagonal is 3 √2 ? |  18 |  12 |  9 |  6";
$q[72]="What is the slope of the line perpendicular to the line represented by the equation 2x + 4y = 12? |  −2 |  2 |  − 1/2 |  1/2";
$q[73]="How many points in the coordinate plane are 3 units from the origin and also equidistant from both the x-axis and the y-axis? |  1 |  2 |  8 |  4";
$q[74]="Ayesha is 25 years old. If Basit’s age is 25% greater than that of Ayesha, then how much percent Ayesha’s age is less than Basit's age? | 40% | 35% | 10% | 20%";
$q[75]="In a class of 500 students, 65% are boys.  20% of the girls and 40% of the boys failed the exam. Total no. of students failed in the exam are | 335 | 270 | 400  | 362";
$q[76]="The population of a village increases at the rate of 20% annually. At the end of 3 years it is 21600, what was the population at the beginning? | 10000 | 12500 | 15000 | 17500";
$q[77]="A man spends 60% of his income. His income is increased by 20% and his expenditure also increases by 10%. Find the percentage decrease in his saving? |  10% |  15% |  20% |  25%";
$q[78]="A student has to get 40 percent marks to pass an examination. He got 60 marks but fails by 20 marks. Find the maximum marks of the examination. |  150 |  200 |  300 |  400";
$q[79]="The population of a town is 15000. It increases by 10 percent in the first year and 20 percent in the second year. But in the third year it decreases by 10 percent. What will be the population after 3 years. |  16820 |  15820 |  17820 | 19820";


$a = array();
$a[0]="b";
$a[1]="d";
$a[2]="b";
$a[3]="c";
$a[4]="a";
$a[5]="d";
$a[6]="d";
$a[7]="a";
$a[8]="d";
$a[9]="b";
$a[10]="a";
$a[11]="c";
$a[12]="d";
$a[13]="b";
$a[14]="a";
$a[15]="b";
$a[16]="b";
$a[17]="c";
$a[18]="c";
$a[19]="a";
$a[20]="d";
$a[21]="a";
$a[22]="a";
$a[23]="a";
$a[24]="c";
$a[25]="b";
$a[26]="b";
$a[27]="b";
$a[28]="c";
$a[29]="c";
$a[30]="b";
$a[31]="b";
$a[32]="a";
$a[33]="d";
$a[34]="a";
$a[35]="c";
$a[36]="a";
$a[37]="c";
$a[38]="d";
$a[39]="c";
$a[40]="d";
$a[41]="d";
$a[42]="c";
$a[43]="b";
$a[44]="b";
$a[45]="c";
$a[46]="b";
$a[47]="c";
$a[48]="c";
$a[49]="b";
$a[50]="a";
$a[51]="c";
$a[52]="c";
$a[53]="b";
$a[54]="c";
$a[55]="b";
$a[56]="b";
$a[57]="b";
$a[58]="c";
$a[59]="c";
$a[60]="d";
$a[61]="c";
$a[62]="d";
$a[63]="b";
$a[64]="d";
$a[65]="c";
$a[66]="b";
$a[67]="a";
$a[68]="b";
$a[69]="c";
$a[70]="b";
$a[71]="b";
$a[72]="b";
$a[73]="d";
$a[74]="d";
$a[75]="a";
$a[76]="b";
$a[77]="a";
$a[78]="b";
$a[79]="c";


?>









